name: 'Azure Login'
description: 'Log in to Azure'

inputs:
  azureClientId:
    description: 'Azure App Registration Client ID'
    required: true
  
  azureClientSecret:
    description: 'Azure App Registration Client Secret'
    required: true

  azureTenantId:
    description: 'Azure Tenant ID'
    required: true

runs:
  using: composite
  steps:
    # Log in to Azure
    - name: Log in to Azure
      shell: pwsh
      run: |
        echo "Logging in to Azure"
        $username = "${{ inputs.azureClientId }}"
        $password = ${env:CLIENT_SECRET} | ConvertTo-SecureString -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential($username, $password)
        Connect-AzAccount -ServicePrincipal -Tenant ${{ inputs.azureTenantId }} -Credential $credential
      env:
        CLIENT_SECRET: ${{ inputs.azureClientSecret }}
