name: 'Azure Login and Automation Install'
description: 'Log in to Azure and install Azure Automation module'

inputs:
  azureClientId:
    description: 'Azure App Registration Client ID'
    required: true
  
  azureClientSecret:
    description: 'Azure App Registration Client Secret'
    required: true

  azureTenantId:
    description: 'Azure Tenant ID'
    required: true

runs:
  using: composite
  steps:
    - name: Set up PowerShell module cache
      id: ps-module-cache
      uses: actions/cache@v3
      with:
        path: "~/.local/share/powershell/Modules"
        key: ${{ runner.os }}-az-automation

    # Install the PowerShell dependencies
    - name: Install Az.Automation PowerShell module
      if: steps.ps-module-cache.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module Az.Automation

    # Log in to Azure
    - name: Log in to Azure
      shell: pwsh
      run: |
        echo "Logging in to Azure"
        $username = "${{ inputs.azureClientId }}"
        $password = ${env:CLIENT_SECRET} | ConvertTo-SecureString -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential($username, $password)
        Connect-AzAccount -ServicePrincipal -Tenant ${{ inputs.azureTenantId }} -Credential $credential
      env:
        CLIENT_SECRET: ${{ inputs.azureClientSecret }}
