name: 'Install Azure Automation PowerShell Module'
description: 'Install Azure Automation PowerShell Module'
runs:
  using: composite
  steps:
    - name: Set up PowerShell module cache
      id: ps-module-cache
      uses: actions/cache@v3
      with:
        path: "~/.local/share/powershell/Modules"
        key: ${{ runner.os }}-az-automation

    # Install the PowerShell dependencies
    - name: Install Az.Automation PowerShell module
      if: steps.ps-module-cache.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module Az.Automation
