name: 'Deploy Azure Automation Runbook'
description: 'Deploys a Runbook to Azure Automation'

inputs:
  automationAccountName:
    description: 'Azure Automation Account Name'
    required: true
  
  azureClientId:
    description: 'Azure App Registration Client ID'
    required: true
  
  azureClientSecret:
    description: 'Azure App Registration Client Secret'
    required: true
    
  azureSubscriptionId:
    description: 'Azure Subscription ID'
    required: true

  azureTenantId:
    description: 'Azure Tenant ID'
    required: true

  resourceGroupName:
    description: 'Resource Group Name where Azure Automation resides'
    required: true
  
  runbookName:
    description: 'Name of the Runbook in Azure Automation'
    required: true
    
  scheduleName:
    description: 'Name of the Azure Automation Schedule to register the Runbook for'
    required: false

  scriptPath:
    description: 'Path to the script to be deployed'
    required: true
    
runs:
  using: composite
  steps:
    # Install the PowerShell dependencies
    - name: Install Az.Automation PowerShell module
      uses: ./.github/actions/install-automation-module

    # Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.azureClientId }}
        tenant-id: ${{ inputs.azureTenantId }}
        subscription-id: ${{ inputs.azureSubscriptionId }}
        enable-AzPSSession: true

    # Deploy script to Azure Automation
    - name: Deploy Script to Azure Automation as a Runbook
      shell: pwsh
      run: |
        echo "Deploying ${{ inputs.scriptPath }} to Azure Automation as a Runbook"
        Import-AzAutomationRunbook -Path ${{ inputs.scriptPath }} -Name "${{ inputs.runbookName }}" -Type PowerShell -AutomationAccountName ${{ inputs.automationAccountName }} -ResourceGroupName ${{ inputs.resourceGroupName }} -Force
        Publish-AzAutomationRunbook -Name "${{ inputs.runbookName }}" -AutomationAccountName ${{ inputs.automationAccountName }} -ResourceGroupName ${{ inputs.resourceGroupName }}

    # Register the Runbook with a Schedule
    - name: Register Runbook with a Schedule
      shell: pwsh
      run: |
        echo "Registering ${{ inputs.runbookName }} with ${{ inputs.scheduleName }} schedule"
        Register-AzAutomationScheduledRunbook -ResourceGroupName ${{ inputs.resourceGroupName }} -AutomationAccountName ${{ inputs.automationAccountName }} -RunbookName "${{ inputs.runbookName }}" -ScheduleName "${{ inputs.scheduleName}}"
