name: Configure Runbook Schedules

on:
  # Manually Trigger
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  deploy:
    name: Deploy Script
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      # Install the PowerShell dependencies
      - name: Install Az.Automation PowerShell module
        uses: ./.github/actions/install-automation-module

      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      # Create Azure Automation Schedules
      - name: Create Azure Automation Schedules
        shell: pwsh
        run: |
          $StartTime = (Get-Date "6:00:00").AddDays(1)
          New-AzAutomationSchedule -ResourceGroupName ${{ vars.AUTOMATION_RESOURCE_GROUP_NAME }} -AutomationAccountName ${{ vars.AUTOMATION_ACCOUNT_NAME }} -Name "Daily 6am UTC" -Description "Executes daily at 6am UTC" -DayInterval 1 -StartTime $StartTime
          [System.DayOfWeek[]]$WeekDays = @([System.DayOfWeek]::Monday)
          New-AzAutomationSchedule -ResourceGroupName ${{ vars.AUTOMATION_RESOURCE_GROUP_NAME }} -AutomationAccountName ${{ vars.AUTOMATION_ACCOUNT_NAME }} -Name "Weekly on Monday 6am UTC" -Description "Executes weekly on Monday at 6am UTC" -WeekInterval 1 -StartTime $StartTime -DaysOfWeek $WeekDays
