name: Deploy Audit Runbooks

on:
  # Trigger on push to main branch
  push:
    branches: [ "main" ]
    paths: 'Audit/**'

  # Trigger on a Pull Request
  pull_request:
    branches: [ "main" ]
    paths: 'Audit/**'

  # Manually Trigger
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Script
    runs-on: ubuntu-latest
    
    # Configure settings for each Script / Runbook
    strategy:
      matrix:
        include:
          - runbookName: Hello-World
            scriptPath: './Audit/hello-world.ps1'
            schedule: Daily
          - runbookName: Goodbye-World
            scriptPath: './Audit/goodbye-world.ps1'
            schedule: Weekly

    # Deploy the Scripts / Runbooks to Azure Automation
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Deploy Script to Azure Automation Runbook
        uses: ./.github/actions/deploy-azure-automation-runbook
        with:
          automationAccountName: ${{ vars.AUTOMATION_ACCOUNT_NAME }}
          azureClientId: ${{ vars.AZURE_CLIENT_ID }}
          azureClientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
          azureTenantId: ${{ vars.AZURE_TENANT_ID }}
          resourceGroupName: ${{ vars.AUTOMATION_RESOURCE_GROUP_NAME }}
          runbookName: ${{ matrix.runbookName }}
          scriptPath: ${{ matrix.scriptPath }}
          scheduleName: ${{ matrix.schedule }}
