name: Deploy Hello World Runbook

on:
  # Trigger on push to main branch
  push:
    branches: [ "main" ]
    paths: 'scripts/**'

  # Trigger on a Pull Request
  pull_request:
    branches: [ "main" ]
    paths: 'scripts/**'

  # Manually Trigger
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Script
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - runbookName: Hello-World
            scriptPath: './scripts/hello-world.ps1'
            schedule: Daily
          - runbookName: Goodbye-World
            scriptPath: './scripts/goodbye-world.ps1'
            schedule: Weekly

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Deploy Script to Azure Automation Runbook
        uses: ./.github/actions/deploy-azure-automation-runbook
        with:
          automationAccountName: ${{ vars.AUTOMATION_ACCOUNT_NAME }}
          azureClientId: ${{ vars.AZURE_CLIENT_ID }}
          azureClientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
          azureTenantId: ${{ vars.AZURE_TENANT_ID }}
          resourceGroupName: ${{ vars.AUTOMATION_RESOURCE_GROUP_NAME }}
          runbookName: ${{ matrix.runbookName }}
          scriptPath: ${{ matrix.scriptPath }}
          schedule: ${{ matrix.schedule }}
